source "https://rubygems.org"

gem 'capybara'
gem 'report_builder'
gem 'cucumber', '~> 3.1', '>= 3.1.2'
gem 'site_prism' , '3.7.3'
gem 'selenium-webdriver', '3.142.7'
gem 'webdrivers'
gem 'upcase'
gem 'rspec'
gem 'syntax'
#
# gem "faker"                                                                                                                                                                                                                                                                                                                                   
# gem "httparty"
# gem "cpf_faker"
